schema_version: 3
backend:
  type: tensorrt_fp16
tensorrt:
  engine_path: /home/orin/edge-ai-local-models/stage_k/selective_fp16_notf32_v1/yolov8n_neudet_trt10.3_fp16_notf32_detectfp32_b1_640.engine
  engine_manifest_path: /home/orin/edge-ai-local-evidence/stage_k/selective_fp16_notf32_v1/m2/engine.manifest.json
  device_id: 0
runtime:
  opencv_num_threads: 1
model:
  contract_path: /home/orin/edge-ai/edge-ai-defect/configs/model_contracts/yolov8n_neudet_frozen.yaml
input:
  type: directory
  directory: /home/orin/edge-ai-local-evidence/stage_k/reference/stage_k_level_b_reference_v1/inputs
output:
  json_path: /home/orin/edge-ai-local-evidence/stage_k/selective_fp16_notf32_v1/m2/runtime_result_unused.json
  console: false
  overwrite: false
postprocess:
  conf_threshold: 0.25
  iou_threshold: 0.45
  max_nms: 30000
  max_det: 300
  max_wh: 7680.0
  agnostic: false
